# Generated by Django 5.0.6 on 2024-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uri', models.TextField()),
                ('client_type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('homepage_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
    ]
