"""empty message

Revision ID: 1a4fcd782624
Revises: aef97363e0bc
Create Date: 2023-11-10 19:46:57.415649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a4fcd782624'
down_revision = 'aef97363e0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('redirect_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('client_type', sa.Integer(), nullable=True))
        batch_op.drop_column('credential')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('credential', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('client_type')
        batch_op.drop_column('redirect_url')
        batch_op.drop_column('client_secret')

    # ### end Alembic commands ###
